name: build app
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: load content
        uses: actions/checkout@v2

      - name: load python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4
          
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: run app
        env: 
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python main.py