name: build bot.py
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: load content
              uses: actions/checkout@v2
              
            - name: load python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10' # install the python version needed
            
            - name: install dependencies
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: start bot
              env:
                TOKEN: ${{ secrets.SECRET }}
              run: python test.py
            - shell: bash
              env:
                SECRET: ${{ secrets.SECRET }}
              run:
                python test.py
